#!/bin/bash

# Decrypt environment variables
export AWS_ACCESS_KEY_ID=`echo "jA0ECQMCYJv0VlvOW9hg0koBKLq2xtNiPHM9u7imKCviFFnfMG2773oOxDCuNijlMMU6B2V698V7cnpVF67Zowerfe0Bw7pGIo+KjUAJK6gEY9YBZErf3Aqa8Q==" | base64 --decode | gpg --batch --passphrase "$MYSQL" 2>/dev/null`
export AWS_SECRET_ACCESS_KEY=`echo "jA0ECQMCyB3rixqOExVg0l4BD0spN1LBQ5arTZm0QW/1uR8A8BArB6uouMTOr2FKy8RItOfQOWw1ttFBfENafz767dI1sPYYSVA577OPrAQ20K/+bPQB6j96qnpVFFkbEZg0I48DMw7i0LirH2s3" | base64 --decode | gpg --batch --passphrase "$MYSQL" 2>/dev/null`
export NETLIFY_ACCESS_TOKEN=`echo "jA0ECQMC8e2/d5vjK7Fg0m0BbVJ2J5DdVFFkFSybxlhYbVQi7XKU/EZ7IhN2f7jRfiY7OB8CfQ0MbGfGDpBNnJh2ha15KOt5BSEehEczwaAvlA9lDtskOZwadxqnQg1jB/906ZUgVZzvCKW5pzre5ien/JQhClGfaCieNGNo" | base64 --decode | gpg --batch --passphrase "$MYSQL" 2>/dev/null`
export NETLIFY_DEPLOY_HOOK=`echo "jA0ECQMClnBuwwF4KCtg0nIBkDBUftw4ojGoQWV4klzhAqN/IUb7+pmaU7RcTDdMkZkVsC5ubNRdTwCBXosdlUITBl6NJAjkiaiCGCZ5vRJvz/f5OPioaZ1RzJOcIWDCvbCuNaqScxkP44TP3NmBXAIBR4STlHOiay9N4Px/qCQag54=" | base64 --decode | gpg --batch --passphrase "$MYSQL" 2>/dev/null`

# Set gopath to something that works
export IMPORT_PATH=github.com/fugiman/api.diff.pics
export GOPATH=`pwd`/.GOPATH
rm -rf .GOPATH
mkdir -p `dirname .GOPATH/src/$IMPORT_PATH`
ln -s ../../../.. .GOPATH/src/$IMPORT_PATH

# Run it
go install $IMPORT_PATH/server
.GOPATH/bin/server
